-- Baseline schema, matching what Hibernate's ddl-auto:update previously generated.
-- From here on, every schema change is a new versioned migration file — never edit
-- this one after it has run anywhere.

CREATE TABLE users (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email          VARCHAR(255) NOT NULL,
    password       VARCHAR(255) NOT NULL,
    display_name   VARCHAR(255) NOT NULL,
    email_verified BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE boards (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(200)  NOT NULL,
    description VARCHAR(2000),
    created_at  TIMESTAMP WITH TIME ZONE   NOT NULL,
    owner_id    BIGINT        NOT NULL,
    CONSTRAINT fk_boards_owner FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX idx_boards_owner_id ON boards (owner_id);

CREATE TABLE board_columns (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title    VARCHAR(100) NOT NULL,
    position INTEGER      NOT NULL,
    board_id BIGINT       NOT NULL,
    CONSTRAINT fk_board_columns_board FOREIGN KEY (board_id) REFERENCES boards (id) ON DELETE CASCADE
);
CREATE INDEX idx_board_columns_board_id ON board_columns (board_id);

CREATE TABLE cards (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(200) NOT NULL,
    description VARCHAR(2000),
    position    INTEGER      NOT NULL,
    priority    VARCHAR(20)  NOT NULL DEFAULT 'MEDIUM',
    column_id   BIGINT       NOT NULL,
    CONSTRAINT fk_cards_column FOREIGN KEY (column_id) REFERENCES board_columns (id) ON DELETE CASCADE
);
CREATE INDEX idx_cards_column_id ON cards (column_id);

CREATE TABLE user_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    token_hash VARCHAR(64)  NOT NULL,
    type       VARCHAR(30)  NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE  NOT NULL,
    revoked    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE  NOT NULL,
    CONSTRAINT uq_user_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_user_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX idx_user_tokens_user_id ON user_tokens (user_id);
